[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/rpc"
  to = "/.netlify/functions/rpc"
  status = 200

[[redirects]]
  from = "/api/invoice"
  to = "/.netlify/functions/invoice"
  status = 200

[[redirects]]
  from = "/api/post"
  to = "/.netlify/functions/post"
  status = 200

[[redirects]]
  from = "/api/purge-test-posts"
  to = "/.netlify/functions/purge-test-posts"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
