[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/invoice"
  to = "/.netlify/functions/invoice"
  status = 200

[[redirects]]
  from = "/api/post"
  to = "/.netlify/functions/post"
  status = 200
